#!/bin/sh

# Notify when below this percentage
warning_level=20

# How often to check battery status, in minutes
check_interval=2

while true; do
  battery_level=$(acpi -b \
    | cut -d, -f2 | cut --characters=2,3,4 \
    | sed 's/%//g')
  charging=$(acpi -b | grep -c "Charging")

  # When battery is low, and not already charging
  if [ $battery_level -lt $warning_level ] &&
     [ $charging -eq 0 ]
  then
    dunstify -t 8000 "Low battery !!"
  fi
  
  sleep ${check_interval}m
done
