#!/bin/sh
#Dy@Ducky
ans=$(echo "" | dmenu -p "Enc or Dec ?")
checkemp(){
if [ -z $1 ];
then 
    exit
fi
}
encrypt(){
    openssl enc -e -aes-256-cbc \
  -salt \
  -pbkdf2 \
  -iter 1000000 \
  -md sha512 \
  -base64 \
  -in $enc \
  -out ${enc}.enc
}
decrypt(){
    openssl enc -d -aes-256-cbc \
  -salt \
  -pbkdf2 \
  -iter 1000000 \
  -md sha512 \
  -base64 \
  -in ${enc} \
  -out $(sed 's/\.enc//' <<< ${enc})
}
checkemp $ans
enc=$(find ~ -type f | dmenu -i -l 15 -p "Select the file to enc/dcr: " | tr -d '\n')
checkemp $enc
case $ans in
    enc)
        encrypt && dunstify "Succefully Encrypted" && xclip -selection clipboard ${enc}.enc
        ;;
    dcr|dc)
        decrypt && xclip -selection clipboard $(sed 's/\.enc//' <<< ${enc}) && dunstify " Succefully Decrypted"
        ;;
    *)
        exit
        ;;
esac
